### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by jekkos**
This PR adds a Dockerfile that allows you to run the meter using Docker. I found it easier to use docker on a synology as it lacks a proper package manager.

### CODE REVIEW

**Review by ahpohl — APPROVED** [review]
Thank you very much for contributing the docker file. Looks good, I trust you that it works (my Synology is too old to support docker to try it out myself)

**Comment by jekkos** [comment]
It does start fine on my synology, but I still have one issue which is that the serial connection to the device seemed to be stuck today. The USB connection seems to be hooked up to a ti_3401 chip for which I compiled the kernel drivers. Currently I'm seeing these messages in the kernel logs.

```
 usb 1-2: ti_interrupt_callback - nonzero urb status, -71
```
Beside this the binary starts and connects to MQTT

```
➜  ~ docker run --device /dev/ttyUSB0 -v $(pwd)/solarmeter.conf:/app/config.conf localhost:5002/solarmeter:latest -c /app/config.conf
Solarmeter v0.1.0 (g1f5ebb0)
Solarmeter is online.
```

Btw really happy to have found this project as you use exactly the same stack as me (mosquitto, grafana, nodered), except for postgres. Instead I will probably use mosquitto -> telegraf -> influxdb to persist the sensor data.

**Comment by jekkos** [comment]
Ok I got past this issue and now see following in the logging 

```
Received serial package with CRC mismatch
```

**Comment by ahpohl** [comment]
I use this [RS485 to USB adapter](https://www.waveshare.com/usb-to-rs232-485-ttl.htm) from waveshare with FTDI FT232RL chipset on an Odroid C4 with kernel 4.9.218 and it works really well. Not sure if it will be recognized on the stock Synology kernel though (on my old one with kernel 3.2.101 it doesn't).

The CRC errors happen sometimes on startup until the serial buffers are fully empty and comms established. Just try restarting the daemon a few times and if that still fails then power cycling the Synology could help as well.

For the software stack, I migrated from influxdb to postgresql a while ago because I wasn't able to build the queries I wanted using the flux language. Postgresql on the other hand has much better documentation and a much more powerful SQL language. For the time series data I use the [timescaledb](https://www.timescale.com/) extension, which has very good [tutorials](https://docs.timescale.com/timescaledb/latest/tutorials/#common-scenarios-for-using-timescaledb).

I have written up the complete [installation](https://github.com/ahpohl/smartmeter/wiki) steps in my sister project [smartmeter](https://github.com/ahpohl/smartmeter), which uses the exact same setup. I can only recommend to take a look at timescaledb. Postgresql is awesome! In case you want to try it, the SQL table definitions and queries for the solarmeter project are in the resource folder.

**Comment by jekkos** [comment]
I'm currently using the builtin USB port on the Aurora inverter. It seems there is a ti_3410 chip behind this one (which is rs232/rs485) according to the documentation I found. I suppose you have connected the rs485 with an internal socket in the inverter instead?

The weird thing is now that I first get a couple of CRC errors, and then the adapter hangs while spamming the kernel logs with this urb message I mentioned before here. I checked the driver code for the ti chip and it seems to [start in rs232](https://github.com/torvalds/linux/blob/278218f6778bc7d6f8b67199446c56cec7ebb841/drivers/usb/serial/ti_usb_3410_5052.c#L614c) by default, so my suspicion is that I need to set it to rs485 mode somehow. Not sure if there is a specific ioctl to do that in this case.


Is the serial data text based or is it binary? If it's the first then I maybe I should just try to open it using a terminal emulator to see if the connection works at least. I saw in your writeup a reference to picocom, did you use it to read a datagram from your adapter?

Timescaledb looks quite powerful, I have never used it but I'm already running a postgres next to influxdb, so I might look into it. I also had a colleague some time ago that was quite happy about it. It indeed seems to have some features that influx has not. The detailed writeup is very useful, thanks for that.

**Comment by ahpohl** [comment]
> I'm currently using the builtin USB port on the Aurora inverter.

Ah, my port is plugged and I never really thought of connecting something to it. I use the RS485 screw terminals inside. To get your Aurora communicating properly I would use a FT232RL based RS485 to USB converter like the one I've shown you and connect to the RS485 terminals of the inverter. The kernel driver for the FT232RL should be included even in older kernels. If not, you have already managed to compile a new kernel driver for your Synology (good job btw).

> I need to set it to rs485 mode somehow

The kernel doesn't care about the serial communication standard whether it is RS232 or RS485. The bytes received by are the same in both cases. The difference between those standards is on the signal level and cannot be mixed (see here: https://www.seeedstudio.com/blog/2019/12/06/what-is-rs485-and-its-difference-between-rs232/).

> Is the serial data text based or is it binary?

The aurora communication protocol is binary data (fixed length data packets)

> It indeed seems to have some features that influx has not.

In flux I was not able to create the monthly data by the exact length of the month (the lengths of the month varies between 28-31 days). The easiest way is to take a 30 day average, but it will not be 100% accurate. In postgres you have no such limits and the monthly production is plotted exactly according to the length of the months.

**Comment by jekkos** [comment]
@ahpohl the serial interface is up now and running on docker, in the end I used the rs485 stick that you suggested. It does connect to the same mcu as the usb port on the right, but the latter does seem to have some driver issues in linux.

Now I see data coming in through MQTT, but also often see this message. ```Read bytes failed: Timeout, inverter could not be reached```. I used an old ethernet cable for the datalink. Do you know if there is any setting I can tune to see if I can make the message disappear?

Next step would be to try and install postgres, but have not made up my mind how my new setup will look like.

**Comment by ahpohl** [comment]
I wouldn't worry about these messages. The data is pulled every 5 seconds so if occasionally a data packet is not transferred it doesn't matter.

It is normal to see the `Read bytes failed: Timeout, inverter could not be reached` message 5 times in a row after the inverter powered down during the night (MCU is off so no comms with the inverter) and occasionally during the day. I sometimes also see `Received serial package with CRC mismatch`. Shortly before shutdown you get `Math error: Attempted to divide by Zero` when the power output is zero.

In the latest master you can now enable serial debug logging. You will see packets are transferred quite fast in a row and I guess  the MCU sometimes chokes. Maybe a short pause between serial transfers in libabbaurora could minimize the errors.

**Comment by jekkos** [comment]
Ok so the poll interval is 5 seconds? In that case I should check my setup as I only see a couple of samples a day in grafana. I used an old ethernet cable with strandred copper, that might not have been the best option..

**Comment by ahpohl** [comment]
I use approx. 5 m shielded CAT7 cable, one pair for A and B and another pair for ground. The others 2 pairs are left unconnected. I guess any 4 wire telephone cable would also do. I haven't found any specific RS485 cable.

**Pull request merged**
